/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/03_water bottle-01-opt.glb -o src/components/models/water-bottle-01/index.tsx -t -k -K -s
*/

import { useGLTF } from '@react-three/drei';
import { JSX } from 'react';
import * as THREE from 'three';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
	nodes: {
		['water-bottle-01']: THREE.Mesh;
		['clear-box']: THREE.Mesh;
	};
	materials: {
		water_bottle: THREE.MeshStandardMaterial;
		transperant: THREE.MeshStandardMaterial;
	};
};

export function WaterBottle01Model(props: JSX.IntrinsicElements['group']) {
	const { nodes, materials } = useGLTF(
		'/03_water bottle-01-opt.glb'
	) as unknown as GLTFResult;
	return (
		<group {...props} dispose={null}>
			<group>
				<mesh
					name="water-bottle-01"
					castShadow
					receiveShadow
					geometry={nodes['water-bottle-01'].geometry}
					material={materials.water_bottle}
					position={[0, 0.076, 0]}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={0.025}
				/>
				<mesh
					name="clear-box"
					castShadow
					receiveShadow
					geometry={nodes['clear-box'].geometry}
					material={materials.transperant}
					position={[0, 0, 0.163]}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={0.025}
				/>
			</group>
		</group>
	);
}

useGLTF.preload('/03_water bottle-01-opt.glb');
