/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/05_coffee-mug-01-opt.glb -o src/components/models/coffee-mug-01/index.tsx -t -k -K -s
*/

import { useGLTF } from '@react-three/drei';
import { JSX } from 'react';
import * as THREE from 'three';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
	nodes: {
		['coffee-mug-01_1']: THREE.Mesh;
		['coffee-mug-01_2']: THREE.Mesh;
		['clear-box']: THREE.Mesh;
	};
	materials: {
		Red_Glaze: THREE.MeshStandardMaterial;
		White_Glaze: THREE.MeshStandardMaterial;
		transperant: THREE.MeshStandardMaterial;
	};
};

export function CoffeeMug01Model(props: JSX.IntrinsicElements['group']) {
	const { nodes, materials } = useGLTF(
		'/05_coffee-mug-01-opt.glb'
	) as unknown as GLTFResult;
	return (
		<group {...props} dispose={null}>
			<group>
				<group
					name="coffee-mug-01"
					position={[0, 0.195, 0]}
					rotation={[Math.PI, 0, Math.PI]}
					scale={[0.003, 0.005, 0.003]}
				>
					<mesh
						name="coffee-mug-01_1"
						castShadow
						receiveShadow
						geometry={nodes['coffee-mug-01_1'].geometry}
						material={materials.Red_Glaze}
					/>
					<mesh
						name="coffee-mug-01_2"
						castShadow
						receiveShadow
						geometry={nodes['coffee-mug-01_2'].geometry}
						material={materials.White_Glaze}
					/>
				</group>
			</group>
		</group>
	);
}

useGLTF.preload('/05_coffee-mug-01-opt.glb');
