/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/dancing-girl-opt.glb -o src/components/models/dancing-girl/index.tsx -k -K -t -s
*/

import { useAnimations, useGLTF } from '@react-three/drei';
import { useGraph } from '@react-three/fiber';
import { JSX, useEffect, useMemo, useRef } from 'react';
import * as THREE from 'three';
import { GLTF, SkeletonUtils } from 'three-stdlib';

type ActionName = 'mixamo.com';

interface GLTFAction extends THREE.AnimationClip {
	name: ActionName;
}

type GLTFResult = GLTF & {
	nodes: {
		Ch03: THREE.SkinnedMesh;
		mixamorigHips: THREE.Bone;
	};
	materials: {
		Ch03_Body: THREE.MeshStandardMaterial;
	};
	animations: GLTFAction[];
};

export function DancingGirlModel(props: JSX.IntrinsicElements['group']) {
	const group = useRef<THREE.Group>(null);
	const { scene, animations } = useGLTF('/dancing-girl-opt.glb');
	const clone = useMemo(() => SkeletonUtils.clone(scene), [scene]);
	const { nodes, materials } = useGraph(clone) as unknown as GLTFResult;
	const { actions } = useAnimations(animations, group);

	useEffect(() => {
		actions['mixamo.com']?.play();
	}, [actions]);

	return (
		<group ref={group} {...props} dispose={null}>
			<group name="Scene">
				<group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
					<primitive object={nodes.mixamorigHips} />
				</group>
				<skinnedMesh
					name="Ch03"
					geometry={nodes.Ch03.geometry}
					material={materials.Ch03_Body}
					skeleton={nodes.Ch03.skeleton}
					rotation={[Math.PI / 2, 0, 0]}
					scale={0.01}
				/>
			</group>
		</group>
	);
}

useGLTF.preload('/dancing-girl-opt.glb');
