/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/01_blue-t-shirt-opt.glb -o src/components/models/blue-t-shirt/index.tsx -t -k -K -s
*/

import { useGLTF } from '@react-three/drei';
import { JSX } from 'react';
import * as THREE from 'three';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
	nodes: {
		['blue-t-shirt-01_1']: THREE.Mesh;
		['blue-t-shirt-01_2']: THREE.Mesh;
		['clear-box']: THREE.Mesh;
	};
	materials: {
		Body: THREE.MeshStandardMaterial;
		shortsleeve: THREE.MeshStandardMaterial;
		transperant: THREE.MeshStandardMaterial;
	};
};

export function BlueTshirtModel(props: JSX.IntrinsicElements['group']) {
	const { nodes, materials } = useGLTF(
		'/01_blue-t-shirt-opt.glb'
	) as unknown as GLTFResult;
	return (
		<group {...props} dispose={null}>
			<group>
				<group
					name="blue-t-shirt-01"
					position={[0, 0.047, 0]}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={0.025}
				>
					<mesh
						name="blue-t-shirt-01_1"
						castShadow
						receiveShadow
						geometry={nodes['blue-t-shirt-01_1'].geometry}
						material={materials.Body}
					/>
					<mesh
						name="blue-t-shirt-01_2"
						castShadow
						receiveShadow
						geometry={nodes['blue-t-shirt-01_2'].geometry}
						material={materials.shortsleeve}
					/>
				</group>
				<mesh
					name="clear-box"
					castShadow
					receiveShadow
					geometry={nodes['clear-box'].geometry}
					material={materials.transperant}
					position={[0, 0, 0.163]}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={0.025}
				/>
			</group>
		</group>
	);
}

useGLTF.preload('/01_blue-t-shirt-opt.glb');
