/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/04_water bottle-02-opt.glb -o src/components/models/water-bottle-02/index.tsx -t -k -K -s
*/

import { useGLTF } from '@react-three/drei';
import { JSX } from 'react';
import * as THREE from 'three';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
	nodes: {
		['water-bottel-02_1']: THREE.Mesh;
		['water-bottel-02_2']: THREE.Mesh;
		['water-bottel-02_3']: THREE.Mesh;
		['water-bottel-02_4']: THREE.Mesh;
		['clear-box']: THREE.Mesh;
		['water-bottel-02-sticker']: THREE.Mesh;
	};
	materials: {
		Chrome_Clean: THREE.MeshStandardMaterial;
		M_02___Default: THREE.MeshStandardMaterial;
		PVC_Black_Matte: THREE.MeshStandardMaterial;
		PVC_Black_Matte0: THREE.MeshStandardMaterial;
		transperant: THREE.MeshStandardMaterial;
		M_02___Default2: THREE.MeshStandardMaterial;
	};
};

export function WaterBottle02Model(props: JSX.IntrinsicElements['group']) {
	const { nodes, materials } = useGLTF(
		'/04_water bottle-02-opt.glb'
	) as unknown as GLTFResult;
	return (
		<group {...props} dispose={null}>
			<group>
				<group
					name="water-bottel-02"
					position={[0, 0.112, 0.004]}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={0.025}
				>
					<mesh
						name="water-bottel-02_1"
						castShadow
						receiveShadow
						geometry={nodes['water-bottel-02_1'].geometry}
						material={materials.Chrome_Clean}
					/>
					<mesh
						name="water-bottel-02_2"
						castShadow
						receiveShadow
						geometry={nodes['water-bottel-02_2'].geometry}
						material={materials.M_02___Default}
					/>
					<mesh
						name="water-bottel-02_3"
						castShadow
						receiveShadow
						geometry={nodes['water-bottel-02_3'].geometry}
						material={materials.PVC_Black_Matte}
					/>
					<mesh
						name="water-bottel-02_4"
						castShadow
						receiveShadow
						geometry={nodes['water-bottel-02_4'].geometry}
						material={materials.PVC_Black_Matte0}
					/>
				</group>
				<mesh
					name="clear-box"
					castShadow
					receiveShadow
					geometry={nodes['clear-box'].geometry}
					material={materials.transperant}
					position={[0, 0, 0.163]}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={0.025}
				/>
				<mesh
					name="water-bottel-02-sticker"
					castShadow
					receiveShadow
					geometry={nodes['water-bottel-02-sticker'].geometry}
					material={materials.M_02___Default2}
					position={[0, -0.226, 0.004]}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={0.025}
				/>
			</group>
		</group>
	);
}

useGLTF.preload('/04_water bottle-02-opt.glb');
