/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/08_plate-opt.glb -o src/components/models/plate/index.tsx -t -k -K -s
*/

import { useGLTF } from '@react-three/drei';
import { JSX } from 'react';
import * as THREE from 'three';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
	nodes: {
		plate: THREE.Mesh;
		['clear-box']: THREE.Mesh;
	};
	materials: {
		plates__0: THREE.MeshPhysicalMaterial;
		transperant: THREE.MeshStandardMaterial;
	};
};

export function PlateModel(props: JSX.IntrinsicElements['group']) {
	const { nodes, materials } = useGLTF(
		'/08_plate-opt.glb'
	) as unknown as GLTFResult;
	return (
		<group {...props} dispose={null}>
			<group>
				<mesh
					name="plate"
					castShadow
					receiveShadow
					geometry={nodes.plate.geometry}
					material={materials.plates__0}
					position={[0, 0.381, 0]}
					scale={0.005}
				/>
				<mesh
					name="clear-box"
					castShadow
					receiveShadow
					geometry={nodes['clear-box'].geometry}
					material={materials.transperant}
					position={[0, 0, 0.163]}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={0.025}
				/>
			</group>
		</group>
	);
}

useGLTF.preload('/08_plate-opt.glb');
