/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/plate-with-plane.glb -o src/components/models/plate/demo.tsx -t -k -K -s
*/

import { Plane, useGLTF, useVideoTexture } from '@react-three/drei';
import { JSX } from 'react';
import * as THREE from 'three';
import { GLTF } from 'three-stdlib';

const vertexShader = `
varying vec2 vUv;
void main() {
    vUv = uv;
    gl_Position = projectionMatrix * modelViewMatrix * vec4(position, 1.0);
}
`;

const fragmentShader = `
uniform sampler2D uTexture;
uniform vec3 uKeyColor;
uniform float uSimilarity;
uniform float uSmoothness;
uniform float uAlpha;   // <-- external opacity control
varying vec2 vUv;

void main() {
    vec4 tex = texture2D(uTexture, vUv);
    vec3 color = tex.rgb;

    float dist = distance(color, uKeyColor);
    float keyAlpha = smoothstep(uSimilarity, uSimilarity + uSmoothness, dist);

    float finalAlpha = keyAlpha * uAlpha;

    gl_FragColor = vec4(color, finalAlpha);
}
`;

type GLTFResult = GLTF & {
	nodes: {
		plate: THREE.Mesh;
		['clear-box']: THREE.Mesh;
		Plane: THREE.Mesh;
	};
	materials: {
		plates__0: THREE.MeshPhysicalMaterial;
		transperant: THREE.MeshStandardMaterial;
	};
};

export function PlateWithScreenModel({
	showHidden,
	...props
}: JSX.IntrinsicElements['group'] & { showHidden?: boolean }) {
	const videoTexture = useVideoTexture('/overlay/plate-2.mp4', {
		muted: true,
		loop: true,
		autoplay: true,
		playsInline: true,
		crossOrigin: 'anonymous',
	});

	const { nodes, materials } = useGLTF(
		'/plate-with-plane.glb'
	) as unknown as GLTFResult;

	return (
		<group {...props} dispose={null}>
			<group name="Scene">
				<mesh
					name="plate"
					castShadow
					receiveShadow
					geometry={nodes.plate.geometry}
					material={materials.plates__0}
					position={[0, 0, 0]}
					scale={0.005}
				/>
				<mesh
					name="clear-box"
					castShadow
					receiveShadow
					geometry={nodes['clear-box'].geometry}
					material={materials.transperant}
					position={[0, 0, 0.163]}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={0.025}
				/>
				{showHidden && (
					<Plane args={[0.5, 0.5]} position={[0, 0, 0.1]}>
						<shaderMaterial
							vertexShader={vertexShader}
							fragmentShader={fragmentShader}
							transparent
							uniforms={{
								uTexture: { value: videoTexture },
								uKeyColor: { value: new THREE.Color(0x00ff00).toArray() },
								uSimilarity: { value: 0.55 },
								uSmoothness: { value: 0.2 },
								uAlpha: { value: 0.5 },
							}}
						/>
					</Plane>
				)}
			</group>
		</group>
	);
}

useGLTF.preload('/plate-with-plane.glb');
