/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/02_polo-t-shirt-opt.glb -o src/components/models/polo-t-shirt/index.tsx -t -k -K -s
*/

import { useGLTF } from '@react-three/drei';
import { JSX } from 'react';
import * as THREE from 'three';
import { GLTF } from 'three-stdlib';
import { FlairBoyModel } from '../flair-boy';

type GLTFResult = GLTF & {
	nodes: {
		['t-shirt-02_1']: THREE.Mesh;
		['t-shirt-02_2']: THREE.Mesh;
	};
	materials: {
		Button: THREE.MeshStandardMaterial;
		Polo_Shirt: THREE.MeshStandardMaterial;
	};
};

export function PoloTshirtModel({
	showHidden,
	...props
}: JSX.IntrinsicElements['group'] & {
	showHidden: boolean;
}) {
	const { nodes, materials } = useGLTF(
		'/02_polo-t-shirt-opt.glb'
	) as unknown as GLTFResult;
	return (
		<group {...props} dispose={null}>
			<group>
				<group
					name="t-shirt-02"
					position={[0, 0, 0]}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={0.025}
				>
					<mesh
						name="t-shirt-02_1"
						castShadow
						receiveShadow
						geometry={nodes['t-shirt-02_1'].geometry}
						material={materials.Button}
					/>
					<mesh
						name="t-shirt-02_2"
						castShadow
						receiveShadow
						geometry={nodes['t-shirt-02_2'].geometry}
						material={materials.Polo_Shirt}
					/>
				</group>
			</group>
			{showHidden && (
				<FlairBoyModel scale={0.25} position={[0.025, 0.125, 0.5]} />
			)}
		</group>
	);
}

useGLTF.preload('/02_polo-t-shirt-opt.glb');
