import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import './globals.css';

const poppins = Poppins({
	variable: '--font-poppins',
	weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

const RootLayout = ({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) => {
	return (
		<html lang="en">
			<body className={`${poppins.variable} overflow-x-hidden! antialiased`}>
				<main className="h-fit min-h-dvh w-fit min-w-dvw overflow-x-hidden!">
					{children}
				</main>
			</body>
		</html>
	);
};

export default RootLayout;
