/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/07_coffee-cup-02-opt.glb -o src/components/models/coffee-cup-02/index.tsx -t -k -K -s
*/

import { useGLTF } from '@react-three/drei';
import { JSX } from 'react';
import * as THREE from 'three';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
	nodes: {
		['coffee-cup-01']: THREE.Mesh;
		['clear-box']: THREE.Mesh;
	};
	materials: {
		Material: THREE.MeshStandardMaterial;
		transperant: THREE.MeshStandardMaterial;
	};
};

export function CoffeeCup02Model(props: JSX.IntrinsicElements['group']) {
	const { nodes, materials } = useGLTF(
		'/07_coffee-cup-02-opt.glb'
	) as unknown as GLTFResult;
	return (
		<group {...props} dispose={null}>
			<group>
				<mesh
					name="coffee-cup-01"
					castShadow
					receiveShadow
					geometry={nodes['coffee-cup-01'].geometry}
					material={materials.Material}
					position={[0, 0.188, 0]}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={0.025}
				/>
				<mesh
					name="clear-box"
					castShadow
					receiveShadow
					geometry={nodes['clear-box'].geometry}
					material={materials.transperant}
					position={[0, 0, 0.163]}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={0.025}
				/>
			</group>
		</group>
	);
}

useGLTF.preload('/07_coffee-cup-02-opt.glb');
