/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/09_cake-opt.glb -o src/components/models/cake/index.tsx -t -k -K -s
*/

import { useGLTF } from '@react-three/drei';
import { JSX } from 'react';
import * as THREE from 'three';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
	nodes: {
		['cake-01_1']: THREE.Mesh;
		['cake-01_2']: THREE.Mesh;
		['cake-01_3']: THREE.Mesh;
		['cake-01_4']: THREE.Mesh;
		['cake-01_5']: THREE.Mesh;
		['cake-01_6']: THREE.Mesh;
		['cake-01_7']: THREE.Mesh;
		['clear-box']: THREE.Mesh;
	};
	materials: {
		Blackberry: THREE.MeshStandardMaterial;
		CakeBase_001: THREE.MeshStandardMaterial;
		Cherry: THREE.MeshStandardMaterial;
		Chocolate_001: THREE.MeshStandardMaterial;
		PLATE: THREE.MeshStandardMaterial;
		rasberry: THREE.MeshStandardMaterial;
		stick: THREE.MeshStandardMaterial;
		transperant: THREE.MeshStandardMaterial;
	};
};

export function CakeModel(props: JSX.IntrinsicElements['group']) {
	const { nodes, materials } = useGLTF(
		'/09_cake-opt.glb'
	) as unknown as GLTFResult;
	return (
		<group {...props} dispose={null}>
			<group>
				<group
					name="cake-01"
					position={[0, 0, 0.181]}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={0.025}
				>
					<mesh
						name="cake-01_1"
						castShadow
						receiveShadow
						geometry={nodes['cake-01_1'].geometry}
						material={materials.Blackberry}
					/>
					<mesh
						name="cake-01_2"
						castShadow
						receiveShadow
						geometry={nodes['cake-01_2'].geometry}
						material={materials.CakeBase_001}
					/>
					<mesh
						name="cake-01_3"
						castShadow
						receiveShadow
						geometry={nodes['cake-01_3'].geometry}
						material={materials.Cherry}
					/>
					<mesh
						name="cake-01_4"
						castShadow
						receiveShadow
						geometry={nodes['cake-01_4'].geometry}
						material={materials.Chocolate_001}
					/>
					<mesh
						name="cake-01_5"
						castShadow
						receiveShadow
						geometry={nodes['cake-01_5'].geometry}
						material={materials.PLATE}
					/>
					<mesh
						name="cake-01_6"
						castShadow
						receiveShadow
						geometry={nodes['cake-01_6'].geometry}
						material={materials.rasberry}
					/>
					<mesh
						name="cake-01_7"
						castShadow
						receiveShadow
						geometry={nodes['cake-01_7'].geometry}
						material={materials.stick}
					/>
				</group>
				<mesh
					name="clear-box"
					castShadow
					receiveShadow
					geometry={nodes['clear-box'].geometry}
					material={materials.transperant}
					position={[0, 0, 0.163]}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={0.025}
				/>
			</group>
		</group>
	);
}

useGLTF.preload('/09_cake-opt.glb');
