/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/jumping-sport-boy-opt.glb -o src/components/models/jumping-sport-boy/index.tsx -k -K -t -s
*/

import * as THREE from 'three';
import React, { JSX, useEffect, useMemo, useRef } from 'react';
import { useGraph } from '@react-three/fiber';
import { useGLTF, useAnimations } from '@react-three/drei';
import { GLTF, SkeletonUtils } from 'three-stdlib';

type ActionName = 'mixamo.com';

interface GLTFAction extends THREE.AnimationClip {
	name: ActionName;
}

type GLTFResult = GLTF & {
	nodes: {
		Ch38_Body: THREE.SkinnedMesh;
		Ch38_Eyelashes: THREE.SkinnedMesh;
		Ch38_Hair: THREE.SkinnedMesh;
		Ch38_Shirt: THREE.SkinnedMesh;
		Ch38_Shoes: THREE.SkinnedMesh;
		Ch38_Shorts: THREE.SkinnedMesh;
		Ch38_Socks: THREE.SkinnedMesh;
		mixamorig5Hips: THREE.Bone;
	};
	materials: {
		Ch38_body: THREE.MeshStandardMaterial;
		Ch38_hair: THREE.MeshStandardMaterial;
	};
	animations: GLTFAction[];
};

export function JumpingSportBoyModel(props: JSX.IntrinsicElements['group']) {
	const group = useRef<THREE.Group>(null);
	const { scene, animations } = useGLTF('/jumping-sport-boy-opt.glb');
	const clone = useMemo(() => SkeletonUtils.clone(scene), [scene]);
	const { nodes, materials } = useGraph(clone) as unknown as GLTFResult;
	const { actions } = useAnimations(animations, group);

	useEffect(() => {
		actions['mixamo.com']?.play();
	}, [actions]);
	return (
		<group ref={group} {...props} dispose={null}>
			<group name="Scene">
				<group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
					<primitive object={nodes.mixamorig5Hips} />
				</group>
				<skinnedMesh
					name="Ch38_Body"
					geometry={nodes.Ch38_Body.geometry}
					material={materials.Ch38_body}
					skeleton={nodes.Ch38_Body.skeleton}
					rotation={[Math.PI / 2, 0, 0]}
					scale={0.01}
				/>
				<skinnedMesh
					name="Ch38_Eyelashes"
					geometry={nodes.Ch38_Eyelashes.geometry}
					material={materials.Ch38_hair}
					skeleton={nodes.Ch38_Eyelashes.skeleton}
					rotation={[Math.PI / 2, 0, 0]}
					scale={0.01}
				/>
				<skinnedMesh
					name="Ch38_Hair"
					geometry={nodes.Ch38_Hair.geometry}
					material={materials.Ch38_hair}
					skeleton={nodes.Ch38_Hair.skeleton}
					rotation={[Math.PI / 2, 0, 0]}
					scale={0.01}
				/>
				<skinnedMesh
					name="Ch38_Shirt"
					geometry={nodes.Ch38_Shirt.geometry}
					material={materials.Ch38_body}
					skeleton={nodes.Ch38_Shirt.skeleton}
					rotation={[Math.PI / 2, 0, 0]}
					scale={0.01}
				/>
				<skinnedMesh
					name="Ch38_Shoes"
					geometry={nodes.Ch38_Shoes.geometry}
					material={materials.Ch38_body}
					skeleton={nodes.Ch38_Shoes.skeleton}
					rotation={[Math.PI / 2, 0, 0]}
					scale={0.01}
				/>
				<skinnedMesh
					name="Ch38_Shorts"
					geometry={nodes.Ch38_Shorts.geometry}
					material={materials.Ch38_body}
					skeleton={nodes.Ch38_Shorts.skeleton}
					rotation={[Math.PI / 2, 0, 0]}
					scale={0.01}
				/>
				<skinnedMesh
					name="Ch38_Socks"
					geometry={nodes.Ch38_Socks.geometry}
					material={materials.Ch38_body}
					skeleton={nodes.Ch38_Socks.skeleton}
					rotation={[Math.PI / 2, 0, 0]}
					scale={0.01}
				/>
			</group>
		</group>
	);
}

useGLTF.preload('/jumping-sport-boy-opt.glb');
