/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/06_coffee-mug-02-opt.glb -o src/components/models/coffee-mug-02/index.tsx -t -k -K -s
*/

import { useGLTF } from '@react-three/drei';
import { JSX } from 'react';
import * as THREE from 'three';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
	nodes: {
		['coffee-mug-02']: THREE.Mesh;
		['clear-box']: THREE.Mesh;
		['coffee-mug-02-photo-sticker']: THREE.Mesh;
	};
	materials: {
		Material: THREE.MeshStandardMaterial;
		transperant: THREE.MeshStandardMaterial;
	};
};

export function CoffeeMug02Model(props: JSX.IntrinsicElements['group']) {
	const { nodes, materials } = useGLTF(
		'/06_coffee-mug-02-opt.glb'
	) as unknown as GLTFResult;
	return (
		<group {...props} dispose={null}>
			<group>
				<mesh
					name="coffee-mug-02"
					castShadow
					receiveShadow
					geometry={nodes['coffee-mug-02'].geometry}
					material={materials.Material}
					position={[0, 0.192, 0]}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={0.004}
				/>
				<mesh
					name="coffee-mug-02-photo-sticker"
					castShadow
					receiveShadow
					geometry={nodes['coffee-mug-02-photo-sticker'].geometry}
					material={materials.Material}
					position={[0, -0.278, 0]}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={0.004}
				/>
			</group>
		</group>
	);
}

useGLTF.preload('/06_coffee-mug-02-opt.glb');
